// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbrqbgjnsppojvcuqhnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicnFiZ2puc3Bwb2p2Y3VxaG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDUwOTgsImV4cCI6MjA2NjQyMTA5OH0.2LluE-cPx1jFIpSZj297kAztduU3AYrODJBvZYAjrV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);